### ISSUE TITLE
Error when pull_date.txt is changed

### ISSUE THREAD

**Issue by AndyMcAliley** [USGS-R/lake-temperature-lstm-static#13]
If the pipeline has been run and then pull_date.txt is changed, Snakemake will throw an error like the following the next time it is run:

```
rule fetch_mntoha_dynamic:
    input: 1_fetch/in/pull_date.txt
    output: 1_fetch/tmp/dynamic_mntoha/inputs_08_N45.50-47.00_W93.00-94.00/nldas_meteo_N45.6875-45.6875_W93.1875-93.1875.csv.zip
    jobid: 9
    wildcards: file=inputs_08_N45.50-47.00_W93.00-94.00/nldas_meteo_N45.6875-45.6875_W93.1875-93.1875.csv.zip
    resources: tmpdir=/var/folders/4f/_lj710zn3sq0ds_860n_ytv8js_f4w/T

Downloading nldas_meteo_N45.6875-45.6875_W93.1875-93.1875.csv.zip to 1_fetch/tmp/dynamic_mntoha/inputs_08_N45.50-47.00_W93.00-94.00
Traceback (most recent call last):
  File "/Users/wmcaliley/codes/lake-temperature-lstm-static-2_model-PR/.snakemake/scripts/tmpsxbx5lgi.sb_fetch.py", line 64, in <module>
    main(snakemake.params['sb_id'], snakemake.output[0])
  File "/Users/wmcaliley/codes/lake-temperature-lstm-static-2_model-PR/.snakemake/scripts/tmpsxbx5lgi.sb_fetch.py", line 60, in main
    response = sb_get(sb, item_id, filename, destination_dir=destination_dir)
  File "/Users/wmcaliley/codes/lake-temperature-lstm-static-2_model-PR/.snakemake/scripts/tmpsxbx5lgi.sb_fetch.py", line 38, in sb_get
    raise FileNotFoundError(f'{sb_data_file} not found on ScienceBase')
FileNotFoundError: nldas_meteo_N45.6875-45.6875_W93.1875-93.1875.csv.zip not found on ScienceBase
```

**Comment by AndyMcAliley** [comment]
Usually, when `mntoha_lake_sequences` is called, it triggers the checkpoint `unzip_archive` in turn. Snakemake knows that it needs to hold off on building the DAG downstream of this operation. The files needed by `mntoha_lake_sequences` are unzipped to a new folder by `unzip_archive`. That new folder is the output of the checkpoint, so once it exists, the checkpoint is satisfied. Once the checkpoint has finished, the DAG is rebuilt, those newly unzipped files are detected, and the pipeline continues correctly. On subsequent runs (say, for `mntoha_lake_sequences` for a different lake) `unzip_archive` gets calls, but it won't run unless the folder containing the necessary unzipped files doesn't exist yet. This behavior is desired - no need to unzip again.

When `pull_date.txt` is changed, for some reason, it seems that the checkpoint `unzip_archive` still signals that it has already run and doesn't need to rerun, even when the inputs to `unzip_archive` have changed. So, the downstream part of the DAG is built prematurely. Perhaps this happens because the output of that checkpoint is a directory, which might not be subject to the same updating rules as files, or maybe it's because `unzip_archive` is a checkpoint and not a rule. 

The error itself occurs when a file from the unzipped archive is requested by `mntoha_lake_sequences`. The unzipped file is out-of-date and needs to be remade. However, the pattern for the unzipped file matches the pattern for the directory it's been unzipped it, so `unzip_archive` is erroneously called as the rule needed to make the file, rather than a precursor to building the DAG. The checkpoint expects its output to be a directory, not a file. So, it mishandles the output. However, the error itself is a symptom of the problem that `unzip_archive` didn't rerun when it should have.

**Comment by AndyMcAliley** [comment]
Currently, the workaround is to remove everything in `1_fetch/out/dynamic_mntoha/`. Then the pipeline runs as expected. 

One possible solution is to change the output of `unzip_archive` to be a supplementary file inside the unzipped directory. It's a bit inelegant, but it could work.
